name: Create auto pull request with template

on:
  push:
    branches-ignore: master

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "master"
          label: Test,bug
          title: "[RELEASE] Create a new Release"
          template: .github/PULL_REQUEST_TEMPLATE/TEST_TEMPLATE.md
